server:
  port: 8080

#spring:
#  profiles:
#    active: dev
#---
spring:
#  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: retail_911
    url: jdbc:mysql://localhost:3306/practice?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Hello World Guys

management:
  endpoints:
    web:
      exposure:
        include: "*"
#---
#spring:
#  profiles: prod
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    password: retail_911
#    url: jdbc:mysql://localhost:3306/practice-prod
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#welcome:
#  message: Hello World Guys
